# Following steps need to be run manually
# sudo curl -L -o /etc/yum.repos.d/gh-cli.repo https://cli.github.com/packages/rpm/gh-cli.repo
# sudo dnf install gh -y
# gh auth login -s admin:org

- name: Set Prompt
  ansible.builtin.shell: set-prompt {{ tool_name }}
 
- name: Add github runner user
  ansible.builtin.user:
    name: github-runner

- name: create runner directory
  ansible.builtin.file:
     path: /actions-runner
     state: directory
     owner: github-runner
     group: github-runner

- name: Download runner
  ansible.builtin.unarchive:
     src: https://github.com/actions/runner/releases/download/v2.321.0/actions-runner-linux-x64-2.321.0.tar.gz
     dest: /actions-runner
     remote_src: yes
     owner: github-runner
     group: github-runner
  
- name: Install libicu
  ansible.builtin.dnf:
     name: libicu
     state: installed

- name: Get token
  ansible.builtin.shell: |
    gh api --method POST -H  "Accept:application/vnd.github+json"  -H  "X-GitHub-Api-Version: 2022-11-28" 
     /orgs/devsecops08/actions/runners/registration-token | jq .token
  register: token
  become_user: ec2-runner

- name : Register runner
  ansible.builtin.shell: | 
    ./config.sh --unattended  --url https://github.com/devsecops08  --token {{ token_stdout }}  --name {{ hostname }} --runnergroup Default
  become_user: github-runner
  args:
   chdir: /actions-runner
  
    
